project/apps/authentication/urls.py
from django.urls import path, include
from apps.authentication.views import auth
from apps.services import djangocas
import django_cas_ng.views

app_name = 'authentication'

urlpatterns = [
    path('signin/',         auth.signin,                                name='signin'),
    path('signout/',        django_cas_ng.views.LogoutView.as_view(),   name='signout'),
    path('signup/',         auth.signup,                                name='signup'),
    path('forgot/',         auth.forgot,                                name='forgot'),
    path('verify/',         auth.verify,                                name='verify'),
    path('reset_password/', auth.reset_password,                        name='reset_password'),

    path('login_cas/',      djangocas.CustomLoginView.as_view(),        name='cas_ng_login'), # Custom Django CAS LOGIN
    path('logout_cas/',     django_cas_ng.views.LogoutView.as_view(),   name='cas_ng_logout'),
    path('callback/',       django_cas_ng.views.CallbackView.as_view(), name='cas_ng_proxy_callback'),
]

project/apps/main/api/urls.py
from django.urls import include, path

from .v1.views import presensi


urlpatterns = [
    path('v1/', include([
        path('presensi/user/<str:username>/', presensi.PresensiUserListAPIView.as_view()),
        path('presensi/user/<str:username>/total', presensi.PresensiUserTotalListAPIView.as_view()),
    ])),
]

project/apps/main/urls.py
from apps.main.views import (account, category, dashboard, jabatan, lembaga,
                             pertemuan, presensi, profile, services, setting,
                             tipe_pertemuan)
from django.contrib.auth.decorators import login_required
from django.urls import include, path

app_name = 'main'

urlpatterns = [
    path('dashboard/',                              dashboard.index,            name='dashboard'),
    path('profile/',                                profile.index,              name='profile'),

    path('services/', include([
        path('setprofilesync/',                     services.setprofilesync,    name='services_setprofilesync'),
    ])),

    path('account/', include([
        # =================================================[ LOAD PAGE ]=================================================
        path('table/',                              account.table,              name='account_table'),
        path('role/',                               account.role,               name='account_role'),
        path('add/',                                account.add,                name='account_add'),
        path('generate/',                           account.generate,           name='account_generate'),
        path('edit/<int:id>/',                      account.edit,               name='account_edit'),
        path('edit_group/<int:id>/',                account.edit_group,         name='account_edit_group'),

        # ==================================================[ SERVICE ]==================================================
        path('delrole/<int:userid>/<int:groupid>/', account.delrole,            name='account_delrole'),
        path('deletelist/',                         account.deletelist,         name='account_deletelist'),
        path('synclist/',                           account.synclist,           name='account_synclist'),
        path('setisactive/<str:mode>/',             account.setisactive,        name='account_setisactive'),
        path('datatable/',                          account.datatable,          name='account_datatable'),
        path('import/',                             account.import_user,        name='account_import'),
        path('data_employee/',                      account.api_data_employee,  name='account_data_employee'),
        path('by_lembaga_json/',                    account.by_lembaga_json,  name='account_by_lembaga_json'),
    ])),


    path('category/', include([
        # =================================================[ LOAD PAGE ]=================================================
        path('table/',                              category.table,             name='category_table'),
        path('add/',                                category.add,               name='category_add'),
        path('edit/<int:id>/',                      category.edit,              name='category_edit'),

        # ==================================================[ SERVICE ]==================================================
        path('deletelist/',                         category.deletelist,        name='category_deletelist'),
    ])),

    path('setting/', include([
        # =================================================[ LOAD PAGE ]=================================================
        path('edit/',                               setting.edit,               name='setting_edit'),

        # ==================================================[ SERVICE ]==================================================
        path('deletefile/<int:id>/',                setting.deletefile,         name='setting_deletefile'),
    ])),

    path('admin/', include([
        path('lembaga/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', lembaga.AdminLembagaListView.as_view(), name='admin.lembaga.table'),
            path('generate/', lembaga.AdminLembagaGenerateView.as_view(), name='admin.lembaga.generate'),
        ])),

        path('jabatan/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', jabatan.AdminJabatanListView.as_view(), name='admin.jabatan.table'),
            path('generate/', jabatan.AdminJabatanGenerateView.as_view(), name='admin.jabatan.generate'),
        ])),

        path('tipe_pertemuan/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', tipe_pertemuan.AdminTipePertemuanListView.as_view(), name='admin.tipe_pertemuan.table'),
            path('add/', tipe_pertemuan.AdminTipePertemuanCreateView.as_view(), name='admin.tipe_pertemuan.add'),
            path('<int:id>/update/', tipe_pertemuan.AdminTipePertemuanUpdateView.as_view(), name='admin.tipe_pertemuan.update'),
            # ==================================================[ SERVICE ]==================================================
            path('deletelist/', tipe_pertemuan.AdminTipePertemuanDeleteListView.as_view(), name='admin.tipe_pertemuan.deletelist'),
        ])),
        path('pertemuan/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', pertemuan.AdminPertemuanListView.as_view(), name='admin.pertemuan.table'),
            path('add/', pertemuan.AdminPertemuanCreateView.as_view(), name='admin.pertemuan.add'),
            path('excel_import/', pertemuan.AdminPertemuanExcelImportView.as_view(), name='admin.pertemuan.excel_import'),
            path('<int:id>/update/', pertemuan.AdminPertemuanUpdateView.as_view(), name='admin.pertemuan.update'),
            path('<int:pertemuan_id>/presensi/table/', presensi.AdminPresensiListView.as_view(), name='admin.presensi.table'),
            # ==================================================[ SERVICE ]==================================================
            path('deletelist/', pertemuan.AdminPertemuanDeleteListView.as_view(), name='admin.pertemuan.deletelist'),
        ])),
        path('presensi/', include([
            path('excel_import/', presensi.AdminPresensiExcelImportV2View.as_view(), name='admin.presensi.excel_import'),
            path('total_excel_import/', presensi.AdminPresensiTotalExcelImportView.as_view(), name='admin.presensi.total_excel_import'),
            # =================================================[ LOAD PAGE ]=================================================
        ])),
    ])),

    path('user/', include([
        path('pertemuan/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', pertemuan.UserPertemuanListView.as_view(), name='user.pertemuan.table'),
            path('<int:id>/presensi/add/', presensi.UserPresensiCreateView.as_view(), name='user.presensi.add'),
            # ==================================================[ SERVICE ]==================================================
            path('table_json/', pertemuan.UserPertemuanListJsonView.as_view(), name='user.pertemuan.table_json'),
        ])),

        path('presensi/', include([
            path('bagan/', presensi.UserPresensiBaganView.as_view(), name='user.presensi.bagan'),
            path('grafik/', presensi.LembagaPresensiGrafikView.as_view(), name='user.presensi.grafik'),
            path('<int:presensi_id>/sertifikat/', presensi.UserPresensiSertifikatView.as_view(), name='user.presensi.sertifikat'),
            # =================================================[ LOAD PAGE ]=================================================
        ])),
    ])),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
import private_storage.urls

urlpatterns = [
    path('', include('apps.landingpage.urls', namespace='landingpage')),
    path('private-media/', include(private_storage.urls)),
    path('hijack/', include('hijack.urls')),
    path('admin/', admin.site.urls),
    path('authentication/', include('apps.authentication.urls', namespace='authentication')),
    path('main/', include('apps.main.urls', namespace='main')),

    path('api/main/', include('apps.main.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
        re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    ]

handler404 = 'apps.landingpage.views.home.error_404'

project/apps/main/forms/category.py
from django import forms
from django.utils.translation import gettext_lazy as _

from apps.services.mixins import FormErrorsMixin
from apps.main.models import Category


class FormCategory(forms.ModelForm, FormErrorsMixin):
    class Meta:
        model   = Category
        fields  = '__all__'
        labels  = {
            'name'        : _('Name'),
            'description' : _('Description'),
        }

project/apps/main/api/v1/views/presensi.py
from apps.main.api.v1.serializers.presensi import (PresensiSerializer,
                                                   PresensiTotalSerializer)
from apps.main.models import Pertemuan, Presensi, TipePertemuan
from apps.services.api.view import (CustomListAPIView, CustomListCreateAPIView,
                                    CustomRetrieveAPIView,
                                    CustomRetrieveDestroyAPIView,
                                    CustomRetrieveUpdateAPIView,
                                    CustomRetrieveUpdateDestroyAPIView)
from django.db.models import Count, ExpressionWrapper, F, FloatField, Q
from django.db.models.functions import Coalesce
from rest_framework.authentication import (BasicAuthentication,
                                           SessionAuthentication)
from rest_framework.permissions import IsAuthenticated


class PresensiUserListAPIView(CustomListCreateAPIView):
    queryset = Presensi.objects.all().order_by('-id')
    serializer_class = PresensiSerializer
    permission_classes = [IsAuthenticated]

    def get(self, request, username):
        self.queryset = Presensi.objects.filter(peserta__username=username).order_by('-id')

        if tahun := request.GET.get('tahun'):
            self.queryset = self.queryset.filter(pertemuan__mulai__year=tahun)

        if tipe_pertemuan := request.GET.get('tipe_pertemuan'):
            self.queryset = self.queryset.filter(pertemuan__tipe_pertemuan__nama=tipe_pertemuan)

        # paginasi queryset
        return self.list(request)


class PresensiUserTotalListAPIView(CustomListCreateAPIView):
    queryset = Presensi.objects.all().order_by('-id')
    serializer_class = PresensiTotalSerializer
    permission_classes = [IsAuthenticated]

    def get(self, request, username):
        tahun = request.GET.get('tahun')

        # Filter untuk total presensi user
        presensi_filter = Q(pertemuan__presensi__peserta__username=username)

        # Filter untuk tahun (berlaku ke semua perhitungan)
        pertemuan_filter = Q()
        if tahun:
            pertemuan_filter &= Q(pertemuan__mulai__year=tahun)
            presensi_filter &= Q(pertemuan__mulai__year=tahun)

        self.queryset = (
            TipePertemuan.objects
            .annotate(
                # Total semua pertemuan per tipe
                total_pertemuan=Count(
                    'pertemuan',
                    filter=pertemuan_filter,
                    distinct=True
                ),

                # Total presensi user
                total_presensi=Count(
                    'pertemuan__presensi',
                    filter=presensi_filter,
                    distinct=True
                ),
            )
            .annotate(
                # Hitung persentase
                persentasi=Coalesce(
                    ExpressionWrapper(
                        F('total_presensi') * 100.0 / F('total_pertemuan'),
                        output_field=FloatField()
                    ),
                    0.0
                )
            )
            .order_by('id')
        )

        return self.list(request)

project/apps/main/views/base.py
from django.contrib.auth.mixins import AccessMixin, LoginRequiredMixin
from django.http import HttpResponseForbidden


# =====================================================================================================
#                                               MIXINS
# =====================================================================================================
def in_grup(user, grup_name):
    if user:
        return user.groups.filter(name=grup_name).count() > 0
    return False


class AdminRequiredMixin(AccessMixin):
    """Mixin untuk membatasi akses hanya untuk grup admin."""
    def dispatch(self, request, *args, **kwargs):
        if not in_grup(request.user, 'admin'):
            return HttpResponseForbidden("Anda tidak memiliki hak akses.")
        return super().dispatch(request, *args, **kwargs)


class CustomTemplateBaseMixin(LoginRequiredMixin):
    """Mixin dasar untuk semua view"""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ===[Select CSS and JS Files]===
        context['datatables']       = True
        context['select2']          = True
        context['summernote']       = False
        context['maxlength']        = False
        context['inputmask']        = False
        context['duallistbox']      = False
        context['moment']           = False
        context['daterange']        = False
        context['chartjs']          = False
        return context

project/apps/main/views/dashboard.py
from json import dumps

from apps.main.models import Jabatan, Lembaga, Pertemuan
from apps.services.decorators import group_required, login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse
from django.db.models import Q


# =====================================================================================================
#                                               LOAD PAGE
# =====================================================================================================
@login_required
def index(request):
    context = {}
    # ===[Select CSS and JS Files]===
    context['datatables']       = False
    context['select2']          = True
    context['summernote']       = False
    context['maxlength']        = False
    context['inputmask']        = False
    context['duallistbox']      = False
    context['moment']           = False
    context['daterange']        = False
    context['chartjs']          = False
    context['chartjsv4']          = True

    # data
    user = request.user
    datajabatan = Jabatan.objects.filter(uniid_penjabat=user.username).values_list('unit__id', flat=True)

    context['data_tahun_pertemuan'] = Pertemuan.objects.values_list('mulai__year', flat=True).distinct().order_by('-mulai__year')
    if user.groups.filter(name='admin').exists():
        context['datalembaga'] = Lembaga.objects.all()
        context['datakaryawan'] = User.objects.all().filter(profile__home_id__isnull=False)
    elif datajabatan:
        context['datalembaga'] = Lembaga.objects.filter(Q(id__in=datajabatan) | Q(superunit__id__in=datajabatan)).distinct()
        datakodelembaga = context['datalembaga'].values_list('kode_lembaga', flat=True)
        context['datakaryawan'] = User.objects.filter(Q(profile__home_id__in=datakodelembaga) | Q(username=request.user.username)).distinct()
    else:
        context['datalembaga'] = Lembaga.objects.filter(kode_lembaga=user.profile.home_id).distinct()
        context['datakaryawan'] = User.objects.filter(username=request.user.username)


    # ===[Render Template]===
    return render(request, 'main/index.html', context)

project/apps/main/templates/main/layout/base.html
<!doctype html>
<html lang="en">

  <head>
    {% include 'main/layout/head.html' %}
    {% block head %}{% endblock %}
  </head>

  <body>
    <div class="body-container">
      <div class="main-container">

        {% include 'main/layout/sidebar.html' %}

        <div role="main" class="main-content">
          {% include 'main/layout/navbar.html' %}

          {% block content %}{% endblock %}

          {% include 'main/layout/footer.html' %}
        </div>

      </div>
    </div>
    
    
    {% include 'main/layout/javascript.html' %}

    
    {% block javascript %}{% endblock %}
  </body>

</html>

project/apps/main/templates/main/layout/footer.html
  
  <footer class="footer" style="height: 3.5rem;">
    <div class="footer-inner">
      <div class="h-100 pt-3 border-t-1 brc-secondary-l3 bgc-white">
        <!-- <span class="text-primary-m2 font-bolder text-120">{{ APP_SHORT_NAME }}</span> -->
        <span class="text-muted">{{ APP_DEVELOPER }} {{ APP_COMPANY_SHORT_NAME }} &copy; <span id="app_year">{{ APP_YEAR }}</span> {{ APP_VERSION }}</span>
        <script>document.getElementById("app_year").innerText = "{{ APP_YEAR }} - " + new Date().getFullYear();</script>

        <!-- <span class="mx-3 action-buttons">
          <a href="#" class="text-blue-m3 text-140"><i class="fab fa-twitter-square"></i></a>
          <a href="#" class="text-blue-d1 text-140"><i class="fab fa-facebook"></i></a>
          <a href="#" class="text-orange text-140"><i class="fa fa-rss-square"></i></a>
        </span> -->
      </div>
    </div><!-- .footer-inner -->

    <div class="footer-tools">
      <a href="#" class="btn-scroll-up btn btn-white brc-black-tp7 px-25 py-2 text-95 border-2 radius-round mb-2 mr-2">
        <i class="fa fa-angle-double-up w-2 h-2"></i>
      </a>
    </div>
  </footer>

project/apps/main/templates/main/layout/head.html
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
    <meta name="robots" content="noindex">
    <base href="../" />

    <title>{{ APP_SHORT_NAME }}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/bootstrap/dist/css/bootstrap.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/@fontawesome/css/all.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'template/dist/css/ace-font.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'template/dist/css/ace.css' %}">

    <link rel="icon" type="image/x-icon" href="{{ APP_FAVICON }}" />

    <link rel="stylesheet" type="text/css" href="{% static 'template/dist/css/ace-themes.css' %}">

    {% if datatables %}
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/datatables.net-buttons-bs4/css/buttons.bootstrap4.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/datatables.net-rowgroup/css/rowGroup.bootstrap.css' %}">
    <style>.dt-buttons .btn-group .dt-button-collection .dropdown-menu { max-height: 200px; overflow-y: auto; }</style>
    {% endif %}

    {% if tinydatepicker %}
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/tiny-date-picker/tiny-date-picker.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/tiny-date-picker/date-range-picker.css' %}">
    {% endif %}

    {% if datetimepicker %}
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css' %}">
    {% endif %}

    {% if select2 %}
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/select2/dist/css/select2.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
    {% endif %}

    {% if chosen %}
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/chosen-js/chosen.css' %}">
    {% endif %}

    {% if dropzone %}
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/dropzone/dist/dropzone.css' %}">
    {% endif %}

    {% if summernote %}
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/summernote/dist/summernote-lite.css' %}">
    {% endif %}

    {% if fullcalendar %}
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/fullcalendar/main.css' %}">
    {% endif %}

    {% if photoswipe %}
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/photoswipe/dist/photoswipe.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/photoswipe/dist/default-skin/default-skin.css' %}">
    {% endif %}

    {% if duallistbox %}
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/bootstrap-duallistbox/dist/bootstrap-duallistbox.css' %}">
    {% endif %}

    {% if daterange %}
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/daterangepicker/daterangepicker.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    {% endif %}

    {% if flatpickr %}
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/flatpickr.min.css' %}">
    {% endif %}

project/apps/main/templates/main/layout/navbar.html
{% load static %}
<nav class="navbar navbar-sm navbar-expand-lg navbar-fixed navbar-darkblue">
  <div class="navbar-inner">


    <div class="d-flex h-100 justify-content-xl-between align-items-center">

      <button type="button" class="btn btn-burger burger-arrowed static collapsed ml-2 d-flex d-xl-none" data-toggle-mobile="sidebar" data-target="#sidebar" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle sidebar">
        <span class="bars text-white-m2"></span>
      </button><!-- mobile sidebar toggler button -->

      <a class="navbar-brand d-xl-none mx-1 text-white text-130 center" href="#">
        <!-- <i class="fas fa-desktop mr-2px text-white-m2"></i> -->
        <img alt="LOGO" src="{{ APP_LOGO }}" class="mx-auto mr-1 align-text-bottom" width="30">
        {{ APP_SHORT_NAME }}
      </a>

      <button type="button" class="btn text-white-m2 btn-burger align-self-center mx-2 d-none d-xl-flex btn-h-light-primary" data-toggle="sidebar" data-target="#sidebar" aria-controls="sidebar" aria-expanded="true" aria-label="Toggle sidebar">
        <span class="bars"></span>
      </button><!-- sidebar toggler button -->

    </div>



    <!-- #navbarMenu toggler -->
    <button class="navbar-toggler ml-1 mr-2 px-1" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navbar menu">
      <img class="mx-0 radius-round border-2 brc-primary-tp3 p-1px" src="{{ request.session.user.image }}" width="36" alt="Image" style="aspect-ratio : 1 / 1;">
    </button>


    <div class="navbar-menu collapse navbar-collapse navbar-backdrop" id="navbarMenu">

      <div class="navbar-nav">
        <ul class="nav has-active-border">

          <li class="nav-item dropdown order-first order-lg-last">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <img id="id-navbar-user-image" class="d-none d-lg-inline-block radius-round border-2 brc-white-tp1 mr-2 w-6" src="{{ request.session.user.image }}" alt="Image" style="aspect-ratio : 1 / 1;">
              <span class="d-inline-block d-lg-none d-xl-inline-block">
                        <span class="text-90" id="id-user-welcome">Welcome,</span>
              <span class="nav-user-name">{{ request.session.user.fullname|title }}</span>
              </span>

              <i class="caret fa fa-angle-down d-none d-xl-block"></i>
              <i class="caret fa fa-angle-left d-block d-lg-none"></i>
            </a>

            <div class="dropdown-menu dropdown-caret dropdown-menu-right dropdown-animated brc-primary-m3 py-1">
              <div class="d-none d-lg-block d-xl-none">
                <div class="dropdown-header">
                  Welcome, {{ request.session.user.fullname|title }}
                </div>
                <div class="dropdown-divider"></div>
              </div>


              <a class="mt-1 dropdown-item btn btn-outline-grey bgc-h-primary-l3 btn-h-light-primary btn-a-light-primary" href="{% url 'main:profile' %}">
                <i class="fa fa-user text-primary-m1 text-105 mr-1"></i>
                Profile
              </a>
              
              {% if request.user.profile.is_dosen %}
              <a class="dropdown-item btn btn-outline-grey bgc-h-secondary-l3 btn-h-light-secondary btn-a-light-secondary" onclick="setprofilesync()">
                <i class="fa-solid fa-rotate text-success-d1 text-105 mr-1"></i>
                Profile Sync
              </a>
              {% endif %}

              <div class="dropdown-divider brc-primary-l2"></div>
              
              <a class="dropdown-item btn btn-outline-grey bgc-h-secondary-l3 btn-h-light-secondary btn-a-light-secondary" href="{% url 'authentication:signout' %}">
                <i class="fa fa-power-off text-warning-d1 text-105 mr-1"></i>
                Logout
              </a>
            </div>
          </li>

        </ul>
      </div>

    </div>



  </div>
</nav>