project/apps/authentication/urls.py
from django.urls import path, include
from apps.authentication.views import auth
from apps.services import djangocas
import django_cas_ng.views

app_name = 'authentication'

urlpatterns = [
    path('signin/',         auth.signin,                                name='signin'),
    path('signout/',        django_cas_ng.views.LogoutView.as_view(),   name='signout'),
    path('signup/',         auth.signup,                                name='signup'),
    path('forgot/',         auth.forgot,                                name='forgot'),
    path('verify/',         auth.verify,                                name='verify'),
    path('reset_password/', auth.reset_password,                        name='reset_password'),

    path('login_cas/',      djangocas.CustomLoginView.as_view(),        name='cas_ng_login'), # Custom Django CAS LOGIN
    path('logout_cas/',     django_cas_ng.views.LogoutView.as_view(),   name='cas_ng_logout'),
    path('callback/',       django_cas_ng.views.CallbackView.as_view(), name='cas_ng_proxy_callback'),
]

project/apps/landingpage/urls.py
from django.urls import path
from apps.landingpage.views import home

app_name = 'landingpage'

urlpatterns = [
  path('',      home.home,       name='home'),
  path('404/',  home.error_404,  name='404')
]

project/apps/main/urls.py
from apps.main.views import (account, category, dashboard, jabatan, lembaga,
                             pertemuan, presensi, profile, services, setting,
                             tipe_pertemuan)
from django.contrib.auth.decorators import login_required
from django.urls import include, path

app_name = 'main'

urlpatterns = [
    path('dashboard/',                              dashboard.index,            name='dashboard'),
    path('profile/',                                profile.index,              name='profile'),

    path('services/', include([
        path('setprofilesync/',                     services.setprofilesync,    name='services_setprofilesync'),
    ])),

    path('account/', include([
        # =================================================[ LOAD PAGE ]=================================================
        path('table/',                              account.table,              name='account_table'),
        path('role/',                               account.role,               name='account_role'),
        path('add/',                                account.add,                name='account_add'),
        path('generate/',                           account.generate,           name='account_generate'),
        path('edit/<int:id>/',                      account.edit,               name='account_edit'),
        path('edit_group/<int:id>/',                account.edit_group,         name='account_edit_group'),

        # ==================================================[ SERVICE ]==================================================
        path('delrole/<int:userid>/<int:groupid>/', account.delrole,            name='account_delrole'),
        path('deletelist/',                         account.deletelist,         name='account_deletelist'),
        path('synclist/',                           account.synclist,           name='account_synclist'),
        path('setisactive/<str:mode>/',             account.setisactive,        name='account_setisactive'),
        path('datatable/',                          account.datatable,          name='account_datatable'),
        path('import/',                             account.import_user,        name='account_import'),
        path('data_employee/',                      account.api_data_employee,  name='account_data_employee'),
        path('by_lembaga_json/',                    account.by_lembaga_json,  name='account_by_lembaga_json'),
    ])),


    path('category/', include([
        # =================================================[ LOAD PAGE ]=================================================
        path('table/',                              category.table,             name='category_table'),
        path('add/',                                category.add,               name='category_add'),
        path('edit/<int:id>/',                      category.edit,              name='category_edit'),

        # ==================================================[ SERVICE ]==================================================
        path('deletelist/',                         category.deletelist,        name='category_deletelist'),
    ])),

    path('setting/', include([
        # =================================================[ LOAD PAGE ]=================================================
        path('edit/',                               setting.edit,               name='setting_edit'),

        # ==================================================[ SERVICE ]==================================================
        path('deletefile/<int:id>/',                setting.deletefile,         name='setting_deletefile'),
    ])),

    path('admin/', include([
        path('lembaga/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', lembaga.AdminLembagaListView.as_view(), name='admin.lembaga.table'),
            path('generate/', lembaga.AdminLembagaGenerateView.as_view(), name='admin.lembaga.generate'),
        ])),

        path('jabatan/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', jabatan.AdminJabatanListView.as_view(), name='admin.jabatan.table'),
            path('generate/', jabatan.AdminJabatanGenerateView.as_view(), name='admin.jabatan.generate'),
        ])),

        path('tipe_pertemuan/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', tipe_pertemuan.AdminTipePertemuanListView.as_view(), name='admin.tipe_pertemuan.table'),
            path('add/', tipe_pertemuan.AdminTipePertemuanCreateView.as_view(), name='admin.tipe_pertemuan.add'),
            path('<int:id>/update/', tipe_pertemuan.AdminTipePertemuanUpdateView.as_view(), name='admin.tipe_pertemuan.update'),
            # ==================================================[ SERVICE ]==================================================
            path('deletelist/', tipe_pertemuan.AdminTipePertemuanDeleteListView.as_view(), name='admin.tipe_pertemuan.deletelist'),
        ])),
        path('pertemuan/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', pertemuan.AdminPertemuanListView.as_view(), name='admin.pertemuan.table'),
            path('add/', pertemuan.AdminPertemuanCreateView.as_view(), name='admin.pertemuan.add'),
            path('excel_import/', pertemuan.AdminPertemuanExcelImportView.as_view(), name='admin.pertemuan.excel_import'),
            path('<int:id>/update/', pertemuan.AdminPertemuanUpdateView.as_view(), name='admin.pertemuan.update'),
            path('<int:pertemuan_id>/presensi/table/', presensi.AdminPresensiListView.as_view(), name='admin.presensi.table'),
            # ==================================================[ SERVICE ]==================================================
            path('deletelist/', pertemuan.AdminPertemuanDeleteListView.as_view(), name='admin.pertemuan.deletelist'),
        ])),
        path('presensi/', include([
            path('excel_import/', presensi.AdminPresensiExcelImportV2View.as_view(), name='admin.presensi.excel_import'),
            path('total_excel_import/', presensi.AdminPresensiTotalExcelImportView.as_view(), name='admin.presensi.total_excel_import'),
            # =================================================[ LOAD PAGE ]=================================================
        ])),
    ])),

    path('user/', include([
        path('pertemuan/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', pertemuan.UserPertemuanListView.as_view(), name='user.pertemuan.table'),
            path('<int:id>/presensi/add/', presensi.UserPresensiCreateView.as_view(), name='user.presensi.add'),
            # ==================================================[ SERVICE ]==================================================
            path('table_json/', pertemuan.UserPertemuanListJsonView.as_view(), name='user.pertemuan.table_json'),
        ])),

        path('presensi/', include([
            path('bagan/', presensi.UserPresensiBaganView.as_view(), name='user.presensi.bagan'),
            path('grafik/', presensi.LembagaPresensiGrafikView.as_view(), name='user.presensi.grafik'),
            path('<int:presensi_id>/sertifikat/', presensi.UserPresensiSertifikatView.as_view(), name='user.presensi.sertifikat'),
            # =================================================[ LOAD PAGE ]=================================================
        ])),
    ])),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
import private_storage.urls

urlpatterns = [
    path('', include('apps.landingpage.urls', namespace='landingpage')),
    path('private-media/', include(private_storage.urls)),
    path('hijack/', include('hijack.urls')),
    path('admin/', admin.site.urls),
    path('authentication/', include('apps.authentication.urls', namespace='authentication')),
    path('main/', include('apps.main.urls', namespace='main')),

    path('api/main/', include('apps.main.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
        re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    ]

handler404 = 'apps.landingpage.views.home.error_404'

project/apps/landingpage/views/home.py
from django.shortcuts import render




# =====================================================================================================
#                                               LOAD PAGE
# =====================================================================================================

def error_404(request, exception=None):
    return render(request,'landingpage/error_404.html')

def home(request):
    return render(request, 'landingpage/index.html')

project/apps/main/views/base.py
from django.contrib.auth.mixins import AccessMixin, LoginRequiredMixin
from django.http import HttpResponseForbidden


# =====================================================================================================
#                                               MIXINS
# =====================================================================================================
def in_grup(user, grup_name):
    if user:
        return user.groups.filter(name=grup_name).count() > 0
    return False


class AdminRequiredMixin(AccessMixin):
    """Mixin untuk membatasi akses hanya untuk grup admin."""
    def dispatch(self, request, *args, **kwargs):
        if not in_grup(request.user, 'admin'):
            return HttpResponseForbidden("Anda tidak memiliki hak akses.")
        return super().dispatch(request, *args, **kwargs)


class CustomTemplateBaseMixin(LoginRequiredMixin):
    """Mixin dasar untuk semua view"""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ===[Select CSS and JS Files]===
        context['datatables']       = True
        context['select2']          = True
        context['summernote']       = False
        context['maxlength']        = False
        context['inputmask']        = False
        context['duallistbox']      = False
        context['moment']           = False
        context['daterange']        = False
        context['chartjs']          = False
        return context

project/apps/landingpage/templates/landingpage/layout/base.html
{% load static %}
<!doctype html>
<html lang="en">

  <head>
    {% include 'landingpage/layout/head.html' %}
    {% block head %}{% endblock %}
  </head>

  <body>
    <div class="body-container">
      <div class="pos-abs" id="scroll-down"></div>
      <div class="pos-abs" id="scroll-up"></div>

      {% include 'landingpage/layout/navbar.html' %}


      <!-- <div class="main-container bgc-white w-100" style="position: absolute;"> -->
      <div class="main-container bgc-white">

        {% block content %}{% endblock %}

      </div>

    </div>

    {% include 'landingpage/layout/javascript.html' %}
    {% block javascript %}{% endblock %}
  </body>

</html>

project/apps/landingpage/templates/landingpage/layout/head.html
{% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
    <base href="../" />

    <title>{{ APP_SHORT_NAME }}</title>

    <!-- include common vendor stylesheets & fontawesome -->
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/bootstrap/dist/css/bootstrap.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/@fontawesome/css/all.min.css' %}">


    <!-- include vendor stylesheets used in "Landing Page 1" page. see "/views//pages/partials/landing-page-1/@vendor-stylesheets.hbs" -->
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/aos/dist/aos.css' %}">


    <!-- include fonts -->
    <link rel="stylesheet" type="text/css" href="{% static 'template/dist/css/ace-font.css' %}">



    <!-- ace.css -->
    <link rel="stylesheet" type="text/css" href="{% static 'template/dist/css/ace.css' %}">


    <!-- favicon -->
    <link rel="icon" type="image/x-icon" href="{{ APP_FAVICON }}" />

    <!-- "Landing Page 1" page styles, specific to this page for demo only -->
    <link rel="stylesheet" type="text/css" href="{% static 'template/views/pages/landing-page-1/@page-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'template/dist/css/ace-themes.css' %}">

    {% if datatables %}
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'template/node_modules/datatables.net-buttons-bs4/css/buttons.bootstrap4.css' %}">
    {% endif %}

project/apps/landingpage/templates/landingpage/layout/javascript.html
{% load static %}
    <!-- include common vendor scripts used in demo pages -->
    <script src="{% static 'template/node_modules/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'template/node_modules/popper.js/dist/umd/popper.js' %}"></script>
    <script src="{% static 'template/node_modules/bootstrap/dist/js/bootstrap.js' %}"></script>


    <!-- include vendor scripts used in "Landing Page 1" page. see "/views//pages/partials/landing-page-1/@vendor-scripts.hbs" -->
    <script src="{% static 'template/node_modules/aos/dist/aos.js' %}"></script>


    <!-- include ace.js -->
    <script src="{% static 'template/dist/js/ace.js' %}"></script>

    <!-- "Landing Page 1" page script to enable its demo functionality -->
    <script src="{% static 'template/views/pages/landing-page-1/@page-script.js' %}"></script>

    <script src="{% static 'template/node_modules/sweetalert2/dist/sweetalert2.all.js' %}"></script>

    {% if datatables %}
    <script src="{% static 'template/node_modules/datatables/media/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'template/node_modules/datatables.net-bs4/js/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'template/node_modules/datatables.net-colreorder/js/dataTables.colReorder.js' %}"></script>
    <script src="{% static 'template/node_modules/datatables.net-select/js/dataTables.select.js' %}"></script>


    <script src="{% static 'template/node_modules/datatables.net-buttons/js/dataTables.buttons.js' %}"></script>
    <script src="{% static 'template/node_modules/datatables.net-buttons-bs4/js/buttons.bootstrap4.js' %}"></script>
    <script src="{% static 'template/node_modules/datatables.net-buttons/js/buttons.html5.js' %}"></script>
    <script src="{% static 'template/node_modules/datatables.net-buttons/js/buttons.print.js' %}"></script>
    <script src="{% static 'template/node_modules/datatables.net-buttons/js/buttons.colVis.js' %}"></script>

    <script src="{% static 'template/node_modules/jszip/jszip.min.js' %}"></script>
    <script src="{% static 'template/node_modules/pdfmake/pdfmake.min.js' %}"></script>
    <script src="{% static 'template/node_modules/pdfmake/vfs_fonts.js' %}"></script>


    <script src="{% static 'template/node_modules/datatables.net-responsive/js/dataTables.responsive.js' %}"></script>
    {% endif %}


    {% if messages %}
        <script>
            function notif(status, title, message, redirect=''){
                if (status && title && message) {
                    if (!redirect || redirect == null || redirect == 'None') {
                        Swal.fire({
                            icon: status,
                            title: title,
                            html: message
                        })
                    } else {
                        Swal.fire({
                            icon: status,
                            title: title,
                            html: message,
                            showCancelButton: true,
                            confirmButtonColor: '#3085d6',
                            cancelButtonColor: '#d33',
                            confirmButtonText: 'Check Data',
                            cancelButtonText: 'Cancel'
                        }).then((result) => {
                            if (result.value) {
                                window.location.replace(redirect);
                            }
                        });
                    }
                }
            }

            {% for msg in messages %}
                notif(`{{ msg.level_tag }}`, `{{ msg.level_tag }}`, `{{ msg|safe }}`)
            {% endfor %}
        </script>
    {% endif %}

project/apps/landingpage/templates/landingpage/layout/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-darkblue navbar-fixed" id="navbar-dark">
  <div class="navbar-inner">
    <div class="container">


      <div class="navbar-intro justify-content-xl-between bgc-transparent">
        <a class="navbar-brand text-white text-180" href="">
          <!-- <i class="fa fa-leaf text-105 text-green-l5 mr-1"></i> -->
          <img alt="LOGO" src="{{ APP_LOGO }}" class="mx-auto mr-1" width="40"/>
          <span style="vertical-align: middle;">{{ APP_SHORT_NAME }}</span>
        </a><!-- /.navbar-brand -->
      </div><!-- /.navbar-intro -->


      <div class="navbar-menu collapse navbar-collapse navbar-backdrop " id="navbarMenu1-dark">

        <div class="navbar-nav">
          <ul class="nav nav-compact-3">


          </ul><!-- /.navbar-nav menu -->
        </div><!-- /.navbar-nav -->

      </div><!-- /.navbar-menu.navbar-collapse -->


      <button type="button" class="d-style btn btn-burger static collapsed mr-2 px-4 navbar-toggler d-flex d-lg-none" data-toggle="collapse" data-target="#navbarMenu2-dark" aria-controls="navbarMenu2-dark" aria-expanded="false" aria-label="Toggle navbar menu">
        <i class="fa fa-caret-down d-collapsed text-80"></i>
        <i class="fa fa-caret-up d-n-collapsed text-80"></i>

        <i class="fa fa-user ml-2"></i>
      </button><!-- mobile navbar toggler button -->


      <div class="navbar-menu collapse navbar-collapse navbar-backdrop" id="navbarMenu2-dark">
        <div class="navbar-nav">
          
          <ul class="nav nav-compact">
            <li class="nav-item dropdown px-lg-2 d-lg-flex flex-column justify-content-center">
              <a class="d-none d-lg-block h-auto btn btn-outline-white btn-bold radius-round border-2 dropdown-toggle px-2 px-xl-3" href="" role="button" aria-haspopup="true" aria-expanded="false">
                Home
              </a>
  
              <a class="d-lg-none nav-link dropdown-toggle" href="" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-caret-right bgc-white text-blue radius-round py-2 px-3 mr-2"></i>
                Home
              </a>
            </li>
         

            {% if request.user.is_authenticated %}
              <li class="nav-item dropdown px-lg-2 d-lg-flex flex-column justify-content-center">
                <a class="d-none d-lg-block h-auto btn btn-outline-white btn-bold radius-round border-2 dropdown-toggle px-2 px-xl-3" href="{% url 'main:dashboard' %}" role="button" aria-haspopup="true" aria-expanded="false">
                  Dashboard
                </a>
    
                <a class="d-lg-none nav-link dropdown-toggle" href="{% url 'main:dashboard' %}" role="button" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-caret-right bgc-white text-blue radius-round py-2 px-3 mr-2"></i>
                  Dashboard
                </a>
              </li>
            {% else %}
              <li class="nav-item dropdown px-lg-2 d-lg-flex flex-column justify-content-center">
                <a class="d-none d-lg-block h-auto btn btn-outline-white btn-bold radius-round border-2 dropdown-toggle px-2 px-xl-3" href="{% url 'authentication:signin' %}" role="button" aria-haspopup="true" aria-expanded="false">
                  Login
                </a>
    
                <a class="d-lg-none nav-link dropdown-toggle" href="{% url 'authentication:signin' %}" role="button" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-caret-right bgc-white text-blue radius-round py-2 px-3 mr-2"></i>
                  Login
                </a>
              </li>
            {% endif %}



          </ul>
        </div>
      </div><!-- .navbar-menu -->



    </div><!-- /.container -->
  </div><!-- /.navbar-inner -->
</nav>