project/apps/main/api/urls.py
from django.urls import include, path

from .v1.views import presensi


urlpatterns = [
    path('v1/', include([
        path('presensi/user/<str:username>/', presensi.PresensiUserListAPIView.as_view()),
        path('presensi/user/<str:username>/total', presensi.PresensiUserTotalListAPIView.as_view()),
    ])),
]

project/apps/main/urls.py
from apps.main.views import (account, category, dashboard, jabatan, lembaga,
                             pertemuan, presensi, profile, services, setting,
                             tipe_pertemuan)
from django.contrib.auth.decorators import login_required
from django.urls import include, path

app_name = 'main'

urlpatterns = [
    path('dashboard/',                              dashboard.index,            name='dashboard'),
    path('profile/',                                profile.index,              name='profile'),

    path('services/', include([
        path('setprofilesync/',                     services.setprofilesync,    name='services_setprofilesync'),
    ])),

    path('account/', include([
        # =================================================[ LOAD PAGE ]=================================================
        path('table/',                              account.table,              name='account_table'),
        path('role/',                               account.role,               name='account_role'),
        path('add/',                                account.add,                name='account_add'),
        path('generate/',                           account.generate,           name='account_generate'),
        path('edit/<int:id>/',                      account.edit,               name='account_edit'),
        path('edit_group/<int:id>/',                account.edit_group,         name='account_edit_group'),

        # ==================================================[ SERVICE ]==================================================
        path('delrole/<int:userid>/<int:groupid>/', account.delrole,            name='account_delrole'),
        path('deletelist/',                         account.deletelist,         name='account_deletelist'),
        path('synclist/',                           account.synclist,           name='account_synclist'),
        path('setisactive/<str:mode>/',             account.setisactive,        name='account_setisactive'),
        path('datatable/',                          account.datatable,          name='account_datatable'),
        path('import/',                             account.import_user,        name='account_import'),
        path('data_employee/',                      account.api_data_employee,  name='account_data_employee'),
        path('by_lembaga_json/',                    account.by_lembaga_json,  name='account_by_lembaga_json'),
    ])),


    path('category/', include([
        # =================================================[ LOAD PAGE ]=================================================
        path('table/',                              category.table,             name='category_table'),
        path('add/',                                category.add,               name='category_add'),
        path('edit/<int:id>/',                      category.edit,              name='category_edit'),

        # ==================================================[ SERVICE ]==================================================
        path('deletelist/',                         category.deletelist,        name='category_deletelist'),
    ])),

    path('setting/', include([
        # =================================================[ LOAD PAGE ]=================================================
        path('edit/',                               setting.edit,               name='setting_edit'),

        # ==================================================[ SERVICE ]==================================================
        path('deletefile/<int:id>/',                setting.deletefile,         name='setting_deletefile'),
    ])),

    path('admin/', include([
        path('lembaga/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', lembaga.AdminLembagaListView.as_view(), name='admin.lembaga.table'),
            path('generate/', lembaga.AdminLembagaGenerateView.as_view(), name='admin.lembaga.generate'),
        ])),

        path('jabatan/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', jabatan.AdminJabatanListView.as_view(), name='admin.jabatan.table'),
            path('generate/', jabatan.AdminJabatanGenerateView.as_view(), name='admin.jabatan.generate'),
        ])),

        path('tipe_pertemuan/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', tipe_pertemuan.AdminTipePertemuanListView.as_view(), name='admin.tipe_pertemuan.table'),
            path('add/', tipe_pertemuan.AdminTipePertemuanCreateView.as_view(), name='admin.tipe_pertemuan.add'),
            path('<int:id>/update/', tipe_pertemuan.AdminTipePertemuanUpdateView.as_view(), name='admin.tipe_pertemuan.update'),
            # ==================================================[ SERVICE ]==================================================
            path('deletelist/', tipe_pertemuan.AdminTipePertemuanDeleteListView.as_view(), name='admin.tipe_pertemuan.deletelist'),
        ])),
        path('pertemuan/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', pertemuan.AdminPertemuanListView.as_view(), name='admin.pertemuan.table'),
            path('add/', pertemuan.AdminPertemuanCreateView.as_view(), name='admin.pertemuan.add'),
            path('excel_import/', pertemuan.AdminPertemuanExcelImportView.as_view(), name='admin.pertemuan.excel_import'),
            path('<int:id>/update/', pertemuan.AdminPertemuanUpdateView.as_view(), name='admin.pertemuan.update'),
            path('<int:pertemuan_id>/presensi/table/', presensi.AdminPresensiListView.as_view(), name='admin.presensi.table'),
            # ==================================================[ SERVICE ]==================================================
            path('deletelist/', pertemuan.AdminPertemuanDeleteListView.as_view(), name='admin.pertemuan.deletelist'),
        ])),
        path('presensi/', include([
            path('excel_import/', presensi.AdminPresensiExcelImportV2View.as_view(), name='admin.presensi.excel_import'),
            path('total_excel_import/', presensi.AdminPresensiTotalExcelImportView.as_view(), name='admin.presensi.total_excel_import'),
            # =================================================[ LOAD PAGE ]=================================================
        ])),
    ])),

    path('user/', include([
        path('pertemuan/', include([
            # =================================================[ LOAD PAGE ]=================================================
            path('table/', pertemuan.UserPertemuanListView.as_view(), name='user.pertemuan.table'),
            path('<int:id>/presensi/add/', presensi.UserPresensiCreateView.as_view(), name='user.presensi.add'),
            # ==================================================[ SERVICE ]==================================================
            path('table_json/', pertemuan.UserPertemuanListJsonView.as_view(), name='user.pertemuan.table_json'),
        ])),

        path('presensi/', include([
            path('bagan/', presensi.UserPresensiBaganView.as_view(), name='user.presensi.bagan'),
            path('grafik/', presensi.LembagaPresensiGrafikView.as_view(), name='user.presensi.grafik'),
            path('<int:presensi_id>/sertifikat/', presensi.UserPresensiSertifikatView.as_view(), name='user.presensi.sertifikat'),
            # =================================================[ LOAD PAGE ]=================================================
        ])),
    ])),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
import private_storage.urls

urlpatterns = [
    path('', include('apps.landingpage.urls', namespace='landingpage')),
    path('private-media/', include(private_storage.urls)),
    path('hijack/', include('hijack.urls')),
    path('admin/', admin.site.urls),
    path('authentication/', include('apps.authentication.urls', namespace='authentication')),
    path('main/', include('apps.main.urls', namespace='main')),

    path('api/main/', include('apps.main.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
        re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    ]

handler404 = 'apps.landingpage.views.home.error_404'

project/apps/main/forms/category.py
from django import forms
from django.utils.translation import gettext_lazy as _

from apps.services.mixins import FormErrorsMixin
from apps.main.models import Category


class FormCategory(forms.ModelForm, FormErrorsMixin):
    class Meta:
        model   = Category
        fields  = '__all__'
        labels  = {
            'name'        : _('Name'),
            'description' : _('Description'),
        }

project/apps/main/forms/groupdetails.py
from django import forms
from django.utils.translation import gettext_lazy as _

from apps.services.mixins import FormErrorsMixin
from apps.authentication.models import GroupDetails


class FormGroupDetails(forms.ModelForm, FormErrorsMixin):
    class Meta:
        model   = GroupDetails
        fields  = ['alias','description']
        labels  = {
            'alias'       : _('Alias'),
            'description' : _('Description'),
        }

project/apps/main/forms/setting.py
from django import forms
from apps.main.models import Setting
from django.utils.translation import gettext_lazy as _


class FormSetting(forms.ModelForm):
    class Meta:
        model   = Setting
        fields  = ['value', 'file']
        labels  = {
            'value' : _('Value'),
            'file' : _('File'),
        }

project/apps/main/api/v1/views/presensi.py
from apps.main.api.v1.serializers.presensi import (PresensiSerializer,
                                                   PresensiTotalSerializer)
from apps.main.models import Pertemuan, Presensi, TipePertemuan
from apps.services.api.view import (CustomListAPIView, CustomListCreateAPIView,
                                    CustomRetrieveAPIView,
                                    CustomRetrieveDestroyAPIView,
                                    CustomRetrieveUpdateAPIView,
                                    CustomRetrieveUpdateDestroyAPIView)
from django.db.models import Count, ExpressionWrapper, F, FloatField, Q
from django.db.models.functions import Coalesce
from rest_framework.authentication import (BasicAuthentication,
                                           SessionAuthentication)
from rest_framework.permissions import IsAuthenticated


class PresensiUserListAPIView(CustomListCreateAPIView):
    queryset = Presensi.objects.all().order_by('-id')
    serializer_class = PresensiSerializer
    permission_classes = [IsAuthenticated]

    def get(self, request, username):
        self.queryset = Presensi.objects.filter(peserta__username=username).order_by('-id')

        if tahun := request.GET.get('tahun'):
            self.queryset = self.queryset.filter(pertemuan__mulai__year=tahun)

        if tipe_pertemuan := request.GET.get('tipe_pertemuan'):
            self.queryset = self.queryset.filter(pertemuan__tipe_pertemuan__nama=tipe_pertemuan)

        # paginasi queryset
        return self.list(request)


class PresensiUserTotalListAPIView(CustomListCreateAPIView):
    queryset = Presensi.objects.all().order_by('-id')
    serializer_class = PresensiTotalSerializer
    permission_classes = [IsAuthenticated]

    def get(self, request, username):
        tahun = request.GET.get('tahun')

        # Filter untuk total presensi user
        presensi_filter = Q(pertemuan__presensi__peserta__username=username)

        # Filter untuk tahun (berlaku ke semua perhitungan)
        pertemuan_filter = Q()
        if tahun:
            pertemuan_filter &= Q(pertemuan__mulai__year=tahun)
            presensi_filter &= Q(pertemuan__mulai__year=tahun)

        self.queryset = (
            TipePertemuan.objects
            .annotate(
                # Total semua pertemuan per tipe
                total_pertemuan=Count(
                    'pertemuan',
                    filter=pertemuan_filter,
                    distinct=True
                ),

                # Total presensi user
                total_presensi=Count(
                    'pertemuan__presensi',
                    filter=presensi_filter,
                    distinct=True
                ),
            )
            .annotate(
                # Hitung persentase
                persentasi=Coalesce(
                    ExpressionWrapper(
                        F('total_presensi') * 100.0 / F('total_pertemuan'),
                        output_field=FloatField()
                    ),
                    0.0
                )
            )
            .order_by('id')
        )

        return self.list(request)

project/apps/main/views/base.py
from django.contrib.auth.mixins import AccessMixin, LoginRequiredMixin
from django.http import HttpResponseForbidden


# =====================================================================================================
#                                               MIXINS
# =====================================================================================================
def in_grup(user, grup_name):
    if user:
        return user.groups.filter(name=grup_name).count() > 0
    return False


class AdminRequiredMixin(AccessMixin):
    """Mixin untuk membatasi akses hanya untuk grup admin."""
    def dispatch(self, request, *args, **kwargs):
        if not in_grup(request.user, 'admin'):
            return HttpResponseForbidden("Anda tidak memiliki hak akses.")
        return super().dispatch(request, *args, **kwargs)


class CustomTemplateBaseMixin(LoginRequiredMixin):
    """Mixin dasar untuk semua view"""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ===[Select CSS and JS Files]===
        context['datatables']       = True
        context['select2']          = True
        context['summernote']       = False
        context['maxlength']        = False
        context['inputmask']        = False
        context['duallistbox']      = False
        context['moment']           = False
        context['daterange']        = False
        context['chartjs']          = False
        return context

project/apps/main/views/dashboard.py
from json import dumps

from apps.main.models import Jabatan, Lembaga, Pertemuan
from apps.services.decorators import group_required, login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse
from django.db.models import Q


# =====================================================================================================
#                                               LOAD PAGE
# =====================================================================================================
@login_required
def index(request):
    context = {}
    # ===[Select CSS and JS Files]===
    context['datatables']       = False
    context['select2']          = True
    context['summernote']       = False
    context['maxlength']        = False
    context['inputmask']        = False
    context['duallistbox']      = False
    context['moment']           = False
    context['daterange']        = False
    context['chartjs']          = False
    context['chartjsv4']          = True

    # data
    user = request.user
    datajabatan = Jabatan.objects.filter(uniid_penjabat=user.username).values_list('unit__id', flat=True)

    context['data_tahun_pertemuan'] = Pertemuan.objects.values_list('mulai__year', flat=True).distinct().order_by('-mulai__year')
    if user.groups.filter(name='admin').exists():
        context['datalembaga'] = Lembaga.objects.all()
        context['datakaryawan'] = User.objects.all().filter(profile__home_id__isnull=False)
    elif datajabatan:
        context['datalembaga'] = Lembaga.objects.filter(Q(id__in=datajabatan) | Q(superunit__id__in=datajabatan)).distinct()
        datakodelembaga = context['datalembaga'].values_list('kode_lembaga', flat=True)
        context['datakaryawan'] = User.objects.filter(Q(profile__home_id__in=datakodelembaga) | Q(username=request.user.username)).distinct()
    else:
        context['datalembaga'] = Lembaga.objects.filter(kode_lembaga=user.profile.home_id).distinct()
        context['datakaryawan'] = User.objects.filter(username=request.user.username)


    # ===[Render Template]===
    return render(request, 'main/index.html', context)

project/apps/main/templates/main/category/table.html
{% extends 'main/layout/base.html' %}
{% load main_tags %}

{% block content %}
  <div class="page-content container container-plus">
    <div class="page-header border-0 pb-3">
      <h1 class="page-title text-primary-d2 text-150">
        {% for data in request.path|split:"/"|slice:"2:4" %}
          {% if forloop.counter == 1 %}
            {{ data|title }}
          {% else %}
            <small class="page-info text-secondary-d2 text-nowrap">
              <i class="fa fa-angle-double-right text-80"></i>
              {{ data|title }}
            </small>
          {% endif %}
        {% endfor %}
      </h1>

      <div class="page-tools mt-3 mt-sm-0 mb-sm-n1">
        
      </div>
    </div>




    <div class="row">
      <div class="col-12 col-sm-12 mt-3 mt-sm-0 cards-container">
        <div class="card dcard overflow-hidden">
          <div class="border-t-3 w-100 brc-primary-m1 radius-t-1"></div>
          <div class="card-header">
            <h5 class="card-title text-110 text-primary-d2 pt-1">
              Table
            </h5>

            <div class="card-toolbar no-border">
              <!-- dataTables button will be inserted here dynamically -->
            </div>
          </div><!-- /.card-header -->

          <form method="post" autocomplete="off">

            <table id="datatable_category" class="d-style w-100 table text-dark-m1 text-95 border-y-1 brc-black-tp11 collapsed dtr-table">
              <!-- add `collapsed` by default ... it will be removed by default -->
              <!-- thead with .sticky-nav -->
              <thead class="sticky-nav text-secondary-m1 text-uppercase text-85">
                <tr>
                  <th class="td-toggle-details border-0 bgc-white shadow-sm">
                    <i class="fa fa-angle-double-down ml-2"></i>
                  </th>
    
                  <th class="border-0 bgc-white pl-3 pl-md-4 shadow-sm">
                    <input type="checkbox" />
                  </th>
    
                  <th class="border-0 bgc-white bgc-h-yellow-l3 shadow-sm">
                    No
                  </th>
    
                  <th class="border-0 bgc-white bgc-h-yellow-l3 shadow-sm">
                    Name
                  </th>
    
                  <th class="border-0 bgc-white bgc-h-yellow-l3 shadow-sm">
                    Description
                  </th>
    
                  <th class="border-0 bgc-white shadow-sm w-2">
                    Action
                  </th>
                </tr>
              </thead>
    
              <tbody class="pos-rel">
                {% if datacategory %}
                {% for data in datacategory %}
                <tr class="d-style bgc-h-default-l4">
                  <td class="td-toggle-details pos-rel">
                    <!-- this empty table cell will show the `+` sign which toggles the hidden cells in responsive (collapsed) mode -->
    
                    <div class="position-lc h-95 ml-1px border-l-3 brc-purple-m1">
                      <!-- this decorative highlight border will be shown only when table is collapsed (responsive) -->
                    </div>
                  </td>
    
                  <td class="pl-3 pl-md-4 align-middle pos-rel">
                    <input type="checkbox" value="{{ data.id }}" />
                    <div class="d-n-collapsed position-lc h-95 ml-1px border-l-3 brc-purple-m1">
                      <!-- this decorative highlight border will be shown only when table is in full mode (not collapsed >> .d-n-collapsed) -->
                    </div>
                  </td>
    
                  <td class="align-middle">
                    {{ forloop.counter }}
                  </td>
    
                  <td class="align-middle">
                    {{ data.name }}
                  </td>
    
                  <td class="align-middle">
                    {{ data.description }}
                  </td>
    
                  <td class="align-middle">
                    <div class="d-flex">
                      <span class="d-lg-inline mx-1">
                        <a href="{% url 'main:category_edit' data.id %}" data-action="edit">
                          <button type="button" data-rel="tooltip" data-action="edit" title="Edit" class="btn btn-outline-warning shadow-sm btn-bgc-white">
                              <i class="fas fa-pen-to-square text-100"></i>
                          </button>
                        </a>
                      </span>
      
                      <span class="d-lg-inline mx-1">
                        <a data-action="delete" onclick="submit_listid(`{% url 'main:category_deletelist' %}`, '{{ data.id }}' )">
                          <button type="button" data-rel="tooltip" data-action="delete" title="Delete" class="btn btn-outline-danger shadow-sm btn-bgc-white">
                              <i class="fas fa-trash-can text-100"></i>
                          </button>
                        </a>
                      </span>
                    </div>
    
                  </td>
                </tr>
                {% endfor %}
                {% endif %}
              </tbody>
            </table>
    
          </form>

        </div><!-- /.card -->
      </div><!-- /.col -->
    </div>

  </div>
{% endblock %}


{% block javascript %}
<script>
  $(document).ready(function(){
    var tableId_category = '#datatable_category'
    var $_table_category = $(tableId_category).DataTable({
      dom:
        "<'row'<'col-12 col-sm-4 pl-2'l><'col-12 col-sm-4'B><'col-12 col-sm-4 pr-2 text-right'f>>" +
        "<'row'<'col-12'tr>>" +
        "<'row'<'col-12 col-md-5'i><'col-12 col-md-7'p>>",
      renderer: 'bootstrap',
      responsive: true,
      classes: {
        sLength: "dataTables_length text-left w-auto",
      },
      buttons: {
        dom: {
          button: {
            className: 'btn' //remove the default 'btn-secondary'
          },
          container: {
            className: 'dt-buttons btn-group bgc-white-tp2 text-right w-auto'
          }
        },

        buttons: [
          {
            "extend": "colvis",
            "text": "<i class='far fa-eye text-125 text-dark-m2' data-toggle='tooltip' title='Show/hide columns'></i> <span class='d-none'>Show/hide columns</span>",
            "className": "btn-light-default btn-bgc-white btn-h-outline-primary btn-a-outline-primary",
            columns: ':not(:first)'
          },
          {
            "extend": "copy",
            "text": "<i class='far fa-copy text-125 text-purple' data-toggle='tooltip' title='Copy to clipboard'></i> <span class='d-none'>Copy to clipboard</span>",
            "className": "btn-light-default btn-bgc-white btn-h-outline-primary btn-a-outline-primary"
          },
          {
            "extend": "csv",
            "text": "<i class='fa fa-database text-125 text-success-m1' data-toggle='tooltip' title='CSV'></i> <span class='d-none'>Export to CSV</span>",
            "className": "btn-light-default btn-bgc-white btn-h-outline-primary btn-a-outline-primary"
          },
          {
            "extend": "excel",
            "text": "<i class='far fa-file-excel text-125 text-success-m1' data-toggle='tooltip' title='Excel'></i> <span class='d-none'>Export to Excel</span>",
            "className": "btn-light-default btn-bgc-white btn-h-outline-primary btn-a-outline-primary"
          },
          {
            "extend": "print",
            "text": "<i class='fa fa-print text-125 text-orange-d1' data-toggle='tooltip' title='Print'></i> <span class='d-none'>Print</span>",
            "className": "btn-light-default btn-bgc-white  btn-h-outline-primary btn-a-outline-primary",
            autoPrint: false,
            message: 'This print was produced using the Print button for DataTables'
          }	,
          {
            "extend": "pdf",
            "text": "<i class='far fa-file-pdf text-125 text-danger-m1' data-toggle='tooltip' title='Export to PDF'></i> <span class='d-none'>Export to PDF</span>",
            "className": "btn-light-default btn-bgc-white btn-h-outline-primary btn-a-outline-primary"
          },
        ]
      },
      // first and last column are not sortable
      columnDefs: [
        {
          orderable: false,
          className: null,
          targets:   [0,1,-1]
        },
      ],
      // multiple row selection
      select: {
        style: 'multis'
      },
      // no specific initial ordering
      order: [],
      language: {
        search: '<i class="fa fa-search pos-abs mt-2 pt-3px ml-35 text-blue-m2"></i>',
        searchPlaceholder: "Search..."
      }
    })
    

    // specify position of table buttons
    $(tableId_category).closest('.card').find('.card-toolbar').append(`
      <a href="{% url 'main:category_add' %}">
        <button data-rel="tooltip" type="button" class="btn radius-round btn-outline-primary border-2 btn-sm ml-2" title="Add New">
          <i class="fa fa-plus"></i>
        </button>
      </a>
      <button data-rel="tooltip" type="button" class="btn radius-round btn-outline-danger border-2 btn-sm ml-2" title="Delete" onclick="submit_listid('{% url 'main:category_deletelist' %}',get_list_id('${tableId_category}'))">
        <i class="far fa-trash-alt"></i>
      </button>
    `)

    $('.dataTables_wrapper').find('.dataTables_filter').find('input').addClass('pl-45 radius-round').removeClass('form-control-sm')


    // helper methods to add/remove bgc-h-* class when selecting/deselecting rows
    var _highlightSelectedRow_category = function(row) {
      row.querySelector('input[type=checkbox]').checked = true
      row.classList.add('bgc-success-l3')
      row.classList.remove('bgc-h-default-l4')
    }
    var _unhighlightDeselectedRow_category = function(row) {
      row.querySelector('input[type=checkbox]').checked = false
      row.classList.remove('bgc-success-l3')
      row.classList.add('bgc-h-default-l4')
    }


    // listen to select/deselect event to highlight rows
    $_table_category.on('select', function (e, dt, type, index) {
      if ( type == 'row' ) {
        var row = $_table_category.row( index ).node()
        _highlightSelectedRow_category(row)
      }
    }).on('deselect', function (e, dt, type, index) {
      if ( type == 'row' ) {
        var row = $_table_category.row( index ).node()
        _unhighlightDeselectedRow_category(row)
      }
    })


    // when clicking the checkbox in table header, select/deselect all rows
    $(tableId_category).on('click', 'th input[type=checkbox]', function () {
      if(this.checked) {
        $_table_category.rows({ search: 'applied' }).select().every(function() {
          _highlightSelectedRow_category(this.node())
        });
      }
      else {
        $_table_category.rows({ search: 'applied' }).deselect().every(function() {
          _unhighlightDeselectedRow_category(this.node())
        })
      }
    })


    // add/remove bgc-h-* class to TH when soring columns
    var previousTh = null
    var toggleTH_highlight_category = function(th) {
      th.classList.toggle('bgc-yellow-l2')
      th.classList.toggle('bgc-h-yellow-l3')
      th.classList.toggle('text-blue-d2')
    }

    $(tableId_category).on('click', 'th:not(.sorting_disabled)', function () {
      if(previousTh != null) toggleTH_highlight_category(previousTh)// unhighlight previous TH
      toggleTH_highlight_category(this)
      previousTh = this
    })


    // don't select row if we click on the "show details" `plus` sign (td)
    $(tableId_category).on('click', 'td.dtr-control', function (e) {
      e.stopPropagation()
    })

  });
</script>



<script>
  $(document).ready(function(){
    var tableHead = document.querySelector('.sticky-nav')
    tableHead.addEventListener('sticky-change', function(e) {
      // when  thead becomes sticky, add is-stuck class to it (which adds a border-bottom to it)
      this.classList.toggle('is-stuck', e.detail.isSticky)
    })


    // don't select row when clicking on the edit icon
    $('a[data-action=edit], a[data-action=delete]').on('click', function(e) {
      // e.preventDefault()
      e.stopPropagation()// don't select
    })

    // add a dark border
    $('.dataTables_wrapper').addClass('border-b-1 border-x-1 brc-default-l2')
    // highlight DataTable header
    // also already done in CSS, but you can use custom colors here
    .find('.row:first-of-type')
    .addClass('border-b-1 brc-default-l3 bgc-blue-l4')
    .next().addClass('mt-n1px')// move the next `.row` up by 1px to go below header's border
    
    // highlight DataTable footer
    $('.dataTables_wrapper').find('.row:last-of-type').addClass('border-t-1 brc-default-l3 mt-n1px bgc-default-l4')


    // if the table has scrollbars, add ace styling to it
    $('.dataTables_scrollBody').aceScroll({color: "grey"})

  });
</script>
{% endblock %}