project/apps/authentication/urls.py
from django.urls import path, include
from apps.authentication.views import auth
from apps.services import djangocas
import django_cas_ng.views

app_name = 'authentication'

urlpatterns = [
    path('signin/',         auth.signin,                                name='signin'),
    path('signout/',        django_cas_ng.views.LogoutView.as_view(),   name='signout'),
    path('signup/',         auth.signup,                                name='signup'),
    path('forgot/',         auth.forgot,                                name='forgot'),
    path('verify/',         auth.verify,                                name='verify'),
    path('reset_password/', auth.reset_password,                        name='reset_password'),

    path('login_cas/',      djangocas.CustomLoginView.as_view(),        name='cas_ng_login'), # Custom Django CAS LOGIN
    path('logout_cas/',     django_cas_ng.views.LogoutView.as_view(),   name='cas_ng_logout'),
    path('callback/',       django_cas_ng.views.CallbackView.as_view(), name='cas_ng_proxy_callback'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
import private_storage.urls

urlpatterns = [
    path('', include('apps.landingpage.urls', namespace='landingpage')),
    path('private-media/', include(private_storage.urls)),
    path('hijack/', include('hijack.urls')),
    path('admin/', admin.site.urls),
    path('authentication/', include('apps.authentication.urls', namespace='authentication')),
    path('main/', include('apps.main.urls', namespace='main')),

    path('api/main/', include('apps.main.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
        re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    ]

handler404 = 'apps.landingpage.views.home.error_404'

project/apps/authentication/models/group_details.py
from django.db import models
from django.contrib.auth.models import Group
from django.db.models.signals import post_save
from django.dispatch import receiver


class GroupDetails(models.Model):
    group           = models.OneToOneField(Group, on_delete=models.CASCADE, related_name='groupdetails', primary_key=True)
    alias           = models.CharField(max_length=100, null=True)
    description     = models.TextField(null=True)

    def __str__(self):
        txt = '{\n'
        txt += 'GROUP_NAME \t: {},\n'.format(str(self.group.name if self.group else self.group))
        txt += 'ALIAS \t: {},\n'.format(str(self.alias))
        txt += 'DESCRIPTION \t: {},\n'.format(str(self.description))
        txt += '}\n'
        return txt


@receiver(post_save, sender=Group)
def create_group_details(sender, instance, created, **kwargs):
    if created:
        GroupDetails.objects.create(group=instance)


@receiver(post_save, sender=Group)
def save_group_details(sender, instance, **kwargs):
    instance.groupdetails.save()

project/apps/authentication/models/profile.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.core.validators import FileExtensionValidator

from apps.services.utils import data_jabfung
from private_storage.fields import PrivateImageField

from uuid import uuid4
import os


def path_image(instance, filename):
    upload_to = 'images/profile'
    ext = filename.split('.')[-1]
    hex = '{}'.format(uuid4().hex)
    filename = '%s.%s' % (hex, ext)
    return os.path.join(upload_to, filename)


class Profile(models.Model):
    user            = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', primary_key=True)
    nip             = models.CharField(max_length=20, null=True, blank=True)
    nidn            = models.CharField(max_length=50, null=True, blank=True)
    ext_email       = models.CharField(max_length=100, null=True, blank=True) # Extra Email
    phone_number    = models.CharField(max_length=15, null=True, blank=True)
    is_dosen        = models.IntegerField(null=True, blank=True)
    home_id         = models.CharField(max_length=20, null=True, blank=True)
    homebase        = models.CharField(max_length=255, null=True, blank=True)
    tanggalmulaimasuk = models.CharField(max_length=255, null=True, blank=True)
    kepegawaian     = models.CharField(max_length=255, null=True, blank=True)
    status          = models.CharField(max_length=255, null=True, blank=True)
    image           = PrivateImageField(null=True, blank=True, upload_to=path_image, validators=[FileExtensionValidator(allowed_extensions=['jpg','jpeg','png','webp'])])
    otp             = models.CharField(max_length=100, null=True, blank=True)


    def __str__(self):
        txt = '{\n'
        txt += 'USERNAME \t: {},\n'.format(str(self.user.username if self.user else self.user))
        txt += 'NIP \t: {},\n'.format(str(self.nip))
        txt += 'NIDN \t: {},\n'.format(str(self.nidn))
        txt += 'EXT_EMAIL \t: {},\n'.format(str(self.ext_email))
        txt += 'PHONE_NUMBER \t: {},\n'.format(str(self.phone_number))
        txt += 'IS_DOSEN \t: {},\n'.format(str(self.is_dosen))
        txt += 'HOME_ID \t: {},\n'.format(str(self.home_id))
        txt += 'HOMEBASE \t: {},\n'.format(str(self.homebase))
        txt += 'KEPEGAWAIAN \t: {},\n'.format(str(self.homebase))
        txt += 'STATUS \t: {},\n'.format(str(self.homebase))
        txt += 'IMAGE \t: {},\n'.format(str(self.image))
        txt += 'OTP \t: {},\n'.format(str(self.otp))
        txt += '}\n'
        return txt


    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return os.path.join(settings.STATIC_URL, 'images/profile/default.png')


    def save(self, *args, **kwargs):
        try:
            this = Profile.objects.get(id=self.id)
            if this.image != self.image:
                this.image.delete()
        except: pass
        super().save(*args, **kwargs)


    def delete(self, *args, **kwargs):
        if self.image:
            self.image.delete()
        super().delete(*args, **kwargs)


    def get_jabfung(self, uid=None):
        data = data_jabfung()
        try:
            if uid:
                return data[uid]
            return data[self.is_dosen]
        except:
            return None


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

project/apps/authentication/templates/authentication/forgot.html
{% extends 'authentication/layout/base.html' %}
{% load static %}

{% block content %}
<div class="main-container container bgc-transparent">

  <div class="main-content minh-100 justify-content-center">
    <div class="p-2 p-md-4">
      <div class="row" id="row-1">
        <div class="col-12 col-xl-10 offset-xl-1 bgc-white shadow radius-1 overflow-hidden">

          <div class="row" id="row-2">

            {% include 'authentication/layout/colintro.html' %}


            <div id="id-col-main" class="col-12 col-lg-7 py-lg-5 bgc-white px-0">
              <div class="tab-pane active show mh-100 px-3 px-lg-0 pb-3" id="id-tab-forgot">
                <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 mt-5 px-0">
                  <h4 class="pt-4 pt-md-0 text-dark-tp4 border-b-1 brc-grey-l2 pb-1 text-130">
                    <i class="fa fa-key text-brown-m1 mr-1"></i>
                    Recover Password
                  </h4>
                </div>


                <form method="post" autocomplete="off" class="form-row mt-4">
                  {% csrf_token %}
                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                    <label class="text-secondary-d3 mb-3">
                      Enter your email address and we'll send you the instructions:
                    </label>
                    <div class="d-flex align-items-center">
                      <input type="email" name="email" class="form-control form-control-lg pr-4 shadow-none" id="id-recover-email" placeholder="Email" />
                      <i class="fa fa-envelope text-grey-m2 ml-n4"></i>
                    </div>
                  </div>

                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 mt-1">
                    <button type="submit" class="btn btn-orange btn-block px-4 btn-bold mt-2 mb-4">
                      Continue
                    </button>
                  </div>
                </form>


                <div class="form-row w-100">
                  <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 d-flex flex-column align-items-center justify-content-center">

                    <hr class="brc-default-l2 mt-0 mb-2 w-100" />
                    <div class="p-0 px-md-2 text-dark-tp4 my-3">
                      <a class="text-blue-d1 text-600 btn-text-slide-x" href="{% url 'authentication:signin' %}">
                        <i class="btn-text-2 fa fa-arrow-left text-110 align-text-bottom mr-2"></i>Back to Login
                      </a>
                    </div>

                  </div>
                </div>


              </div>
            </div>

          </div><!-- /.row -->

        </div><!-- /.col -->
      </div><!-- /.row -->

      {% include 'authentication/layout/copyright.html' %}
    </div>
  </div>

</div>
{% endblock %}

project/apps/authentication/templates/authentication/reset_password.html
{% extends 'authentication/layout/base.html' %}
{% load static %}

{% block content %}
<div class="main-container container bgc-transparent">

  <div class="main-content minh-100 justify-content-center">
    <div class="p-2 p-md-4">
      <div class="row" id="row-1">
        <div class="col-12 col-xl-10 offset-xl-1 bgc-white shadow radius-1 overflow-hidden">

          <div class="row" id="row-2">

            {% include 'authentication/layout/colintro.html' %}


            <div id="id-col-main" class="col-12 col-lg-7 py-lg-5 bgc-white px-0">
              <div class="tab-pane active show mh-100 px-3 px-lg-0 pb-3" id="id-tab-forgot">
                <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 mt-5 px-0">
                  <h4 class="pt-4 pt-md-0 text-dark-tp4 border-b-1 brc-grey-l2 pb-1 text-130">
                    <i class="fa fa-key text-brown-m1 mr-1"></i>
                    Reset Password
                  </h4>
                </div>


                <form method="post" autocomplete="off" class="form-row mt-4">
                  {% csrf_token %}
                  <input type="hidden" name="email" value="{{ email }}">
                  <input type="hidden" name="otp" value="{{ otp }}">

                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                    <div class="d-flex align-items-center input-floating-label text-success brc-success-m2">
                      <input placeholder="{{ formresetpassword.password1.name }}" name="{{ formresetpassword.password1.name }}" value="{{ formresetpassword.password1.value|default_if_none:'' }}" type="password" class="form-control form-control-lg pr-4 shadow-none" id="{{ formresetpassword.password1.id_for_label }}" required/>
                      <i class="fa fa-key text-grey-m2 ml-n4"></i>
                      <label class="floating-label text-grey-l1 text-100 ml-n3" for="{{ formresetpassword.password1.id_for_label }}">
                        {{ formresetpassword.password1.label }}
                      </label>
                    </div>
                  </div>


                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                    <div class="d-flex align-items-center input-floating-label text-success brc-success-m2">
                      <input placeholder="{{ formresetpassword.password2.name }}" name="{{ formresetpassword.password2.name }}" value="{{ formresetpassword.password2.value|default_if_none:'' }}" type="password" class="form-control form-control-lg pr-4 shadow-none" id="{{ formresetpassword.password2.id_for_label }}" required/>
                      <i class="fas fa-sync-alt text-grey-m2 ml-n4"></i>
                      <label class="floating-label text-grey-l1 text-100 ml-n3" for="{{ formresetpassword.password2.id_for_label }}">
                        {{ formresetpassword.password2.label }}
                      </label>
                    </div>
                  </div>

                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 mt-1">
                    <button type="submit" class="btn btn-orange btn-block px-4 btn-bold mt-2 mb-4">
                      Submit
                    </button>
                  </div>
                </form>


                <div class="form-row w-100">
                  <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 d-flex flex-column align-items-center justify-content-center">

                    <hr class="brc-default-l2 mt-0 mb-2 w-100" />
                    <div class="p-0 px-md-2 text-dark-tp4 my-3">
                      <a class="text-blue-d1 text-600 btn-text-slide-x" href="{% url 'authentication:signin' %}">
                        <i class="btn-text-2 fa fa-arrow-left text-110 align-text-bottom mr-2"></i>Back to Login
                      </a>
                    </div>

                  </div>
                </div>


              </div>
            </div>

          </div><!-- /.row -->

        </div><!-- /.col -->
      </div><!-- /.row -->

      {% include 'authentication/layout/copyright.html' %}
    </div>
  </div>

</div>
{% endblock %}

project/apps/authentication/templates/authentication/signin.html
{% extends 'authentication/layout/base.html' %}
{% load static %}

{% block content %}
<div class="main-container container bgc-transparent">

  <div class="main-content minh-100 justify-content-center">
    <div class="p-2 p-md-4">
      <div class="row" id="row-1">
        <div class="col-12 col-xl-10 offset-xl-1 bgc-white shadow radius-1 overflow-hidden">

          <div class="row" id="row-2">

            {% include 'authentication/layout/colintro.html' %}


            <div id="id-col-main" class="col-12 col-lg-7 py-lg-5 bgc-white px-0">
              <div class="tab-pane active show mh-100 px-3 px-lg-0 pb-3" id="id-tab-login">
                <!-- show this in desktop -->
                <div class="d-none d-lg-block col-md-6 offset-md-3 mt-lg-4 px-0">
                  <h4 class="text-dark-tp4 border-b-1 brc-secondary-l2 pb-1 text-130">
                    <i class="fa fa-coffee text-orange-m1 mr-1"></i>
                      Welcome Back
                    </h4>
                </div>

                <!-- show this in mobile device -->
                <div class="d-lg-none text-secondary-m1 my-4 text-center">
                  <a class="mt-5 mb-2" href="">
                    <img src="{{ APP_LOGO }}" alt="LOGO" class="img-fluid mx-auto d-block mb-2" width="100px">
                  </a>
                  <h1 class="text-170">
                    <span class="text-blue-d1 text-80">
                      {{ APP_SHORT_NAME }}
                    </span>
                  </h1>

                  Welcome back
                </div>


                <form method="post" autocomplete="off" class="form-row mt-4">
                  {% csrf_token %}
                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                    <div class="d-flex align-items-center input-floating-label text-blue brc-blue-m2">
                      <input placeholder="{{ formsignin.username.name }}" name="{{ formsignin.username.name }}" value="{{ formsignin.username.value|default_if_none:'' }}" type="text" class="form-control form-control-lg pr-4 shadow-none" id="{{ formsignin.username.id_for_label }}" required/>
                      <i class="fa fa-user text-grey-m2 ml-n4"></i>
                      <label class="floating-label text-grey-l1 ml-n3" for="{{ formsignin.username.id_for_label }}">
                        {{ formsignin.username.label }}
                      </label>
                    </div>
                  </div>


                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 mt-2 mt-md-1">
                    <div class="d-flex align-items-center input-floating-label text-blue brc-blue-m2">
                      <input placeholder="{{ formsignin.password.name }}" name="{{ formsignin.password.name }}" value="{{ formsignin.password.value|default_if_none:'' }}" type="password" class="form-control form-control-lg pr-4 shadow-none" id="{{ formsignin.password.id_for_label }}" required/>
                      <i class="fa fa-key text-grey-m2 ml-n4"></i>
                      <label class="floating-label text-grey-l1 ml-n3" for="{{ formsignin.password.id_for_label }}">
                        {{ formsignin.password.label }}
                      </label>
                    </div>
                  </div>

                  {% if email_config_available %}
                  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 text-right text-md-right mt-n2 mb-2">
                    <a href="{% url 'authentication:forgot' %}" class="text-primary-m1 text-95">
                      Forgot Password?
                    </a>
                  </div>
                  {% endif %}


                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                    <label class="d-inline-block mt-3 mb-0 text-dark-l1">
                      <input type="checkbox" class="mr-1" id="id-remember-me" />
                      Remember me
                    </label>

                    <button type="submit" class="btn btn-primary btn-block px-4 btn-bold mt-2">
                      Sign In
                    </button>
                  </div>

                  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 d-flex flex-column align-items-center justify-content-center">
                    <hr class="brc-default-l2 w-100 mb-2" />
                    <div class="mt-n4 bgc-white-tp2 px-3 py-1 text-secondary-d3 text-90">Or Login With</div>
                  </div>

                  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 flex-column align-items-center justify-content-center">
                    <a href="{% url 'authentication:cas_ng_login' %}?next={{ request.GET.next|urlencode }}">
                      <button type="button" class="btn btn-orange btn-block px-4 btn-bold mt-2 mb-4">
                          <i class="fas fa-arrow-right-to-bracket mr-1"></i>
                          UMS CAS
                      </button>
                  </a>
                  </div>
                </form>


                <div class="form-row">
                  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 d-flex flex-column align-items-center justify-content-center">

                    <hr class="brc-default-l2 mt-0 mb-2 w-100" />

                    <div class="p-0 px-md-2 text-dark-tp3 my-3">
                      Not a member?
                      <a class="text-success-m1 text-600 mx-1" href="{% url 'authentication:signup' %}">
                        Signup now
                      </a>
                    </div>

                  </div>
                </div>

              </div>
            </div>

          </div><!-- /.row -->

        </div><!-- /.col -->
      </div><!-- /.row -->

      {% include 'authentication/layout/copyright.html' %}
    </div>
  </div>

</div>
{% endblock %}

project/apps/authentication/templates/authentication/signup.html
{% extends 'authentication/layout/base.html' %}
{% load static %}

{% block content %}
<div class="main-container container bgc-transparent">

  <div class="main-content minh-100 justify-content-center">
    <div class="p-2 p-md-4">
      <div class="row" id="row-1">
        <div class="col-12 col-xl-10 offset-xl-1 bgc-white shadow radius-1 overflow-hidden">

          <div class="row" id="row-2">

            {% include 'authentication/layout/colintro.html' %}


            <div id="id-col-main" class="col-12 col-lg-7 py-lg-5 bgc-white px-0">
              <div class="tab-pane active show mh-100 px-3 px-lg-0 pb-3" id="id-tab-signup">

                <!-- show this in desktop -->
                <div class="d-none d-lg-block col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 mt-lg-4 px-0">
                  <h4 class="text-dark-tp4 border-b-1 brc-grey-l1 pb-1 text-130">
                    <i class="fa fa-user text-purple mr-1"></i>
                    Create an Account
                  </h4>
                </div>

                <!-- show this in mobile device -->
                <div class="d-lg-none text-secondary-m1 my-4 text-center">
                  <a class="mt-5 mb-2" href="">
                    <img src="{{ APP_LOGO }}" alt="LOGO" class="img-fluid mx-auto d-block mb-2" width="100px">
                  </a>
                  <h1 class="text-170">
                    <span class="text-blue-d1">{{ APP_SHORT_NAME }}</span>
                  </h1>

                  Create an Account
                </div>


                <form method="post" autocomplete="off" class="form-row mt-4">
                  {% csrf_token %}
                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 mt-1">
                    <div class="row pl-3 pr-3">
                      <div class="col-6 d-flex align-items-center input-floating-label text-success brc-success-m2 pl-0">
                        <input placeholder="{{ formsignup.first_name.name }}" name="{{ formsignup.first_name.name }}" value="{{ formsignup.first_name.value|default_if_none:'' }}" type="text" class="form-control form-control-lg pr-4 shadow-none" id="{{ formsignup.first_name.id_for_label }}" required/>
                        <i class="far fa-user text-grey-m2 ml-n4"></i>
                        <label class="floating-label text-grey-l1 text-100 ml-n3" for="{{ formsignup.first_name.id_for_label }}">
                          {{ formsignup.first_name.label }}
                        </label>
                      </div>
  
                      <div class="col-6 d-flex align-items-center input-floating-label text-success brc-success-m2 p-0">
                        <input placeholder="{{ formsignup.last_name.name }}" name="{{ formsignup.last_name.name }}" value="{{ formsignup.last_name.value|default_if_none:'' }}" type="text" class="form-control form-control-lg pr-4 shadow-none" id="{{ formsignup.last_name.id_for_label }}" />
                        <i class="far fa-user text-grey-m2 ml-n4"></i>
                        <label class="floating-label text-grey-l1 text-100 ml-n3" for="{{ formsignup.last_name.id_for_label }}">
                          {{ formsignup.last_name.label }}
                        </label>
                      </div>
                    </div>
                  </div>


                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2">
                    <div class="d-flex align-items-center input-floating-label text-success brc-success-m2">
                      <input placeholder="{{ formsignup.email.name }}" name="{{ formsignup.email.name }}" value="{{ formsignup.email.value|default_if_none:'' }}" type="email" class="form-control form-control-lg pr-4 shadow-none" id="{{ formsignup.email.id_for_label }}" required/>
                      <i class="fa fa-envelope text-grey-m2 ml-n4"></i>
                      <label class="floating-label text-grey-l1 text-100 ml-n3" for="{{ formsignup.email.id_for_label }}">
                        {{ formsignup.email.label }}
                      </label>
                    </div>
                  </div>


                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 mt-1">
                    <div class="d-flex align-items-center input-floating-label text-success brc-success-m2">
                      <input placeholder="{{ formsignup.username.name }}" name="{{ formsignup.username.name }}" value="{{ formsignup.username.value|default_if_none:'' }}" type="text" class="form-control form-control-lg pr-4 shadow-none" id="{{ formsignup.username.id_for_label }}" required/>
                      <i class="fa fa-user text-grey-m2 ml-n4"></i>
                      <label class="floating-label text-grey-l1 text-100 ml-n3" for="{{ formsignup.username.id_for_label }}">
                        {{ formsignup.username.label }}
                      </label>
                    </div>
                  </div>


                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 mt-1">
                    <div class="d-flex align-items-center input-floating-label text-success brc-success-m2">
                      <input placeholder="{{ formsignup.password1.name }}" name="{{ formsignup.password1.name }}" value="{{ formsignup.password1.value|default_if_none:'' }}" type="password" class="form-control form-control-lg pr-4 shadow-none" id="{{ formsignup.password1.id_for_label }}" required/>
                      <i class="fa fa-key text-grey-m2 ml-n4"></i>
                      <label class="floating-label text-grey-l1 text-100 ml-n3" for="{{ formsignup.password1.id_for_label }}">
                        {{ formsignup.password1.label }}
                      </label>
                    </div>
                  </div>


                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 mt-1">
                    <div class="d-flex align-items-center input-floating-label text-success brc-success-m2">
                      <input placeholder="{{ formsignup.password2.name }}" name="{{ formsignup.password2.name }}" value="{{ formsignup.password2.value|default_if_none:'' }}" type="password" class="form-control form-control-lg pr-4 shadow-none" id="{{ formsignup.password2.id_for_label }}" required/>
                      <i class="fas fa-sync-alt text-grey-m2 ml-n4"></i>
                      <label class="floating-label text-grey-l1 text-100 ml-n3" for="{{ formsignup.password2.id_for_label }}">
                        {{ formsignup.password2.label }}
                      </label>
                    </div>
                  </div>


                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 mt-1">
                    <div class="d-flex align-items-center input-floating-label text-success brc-success-m2">
                      <input placeholder="{{ formsignupprofile.phone_number.name }}" name="{{ formsignupprofile.phone_number.name }}" value="{{ formsignupprofile.phone_number.value|default_if_none:'' }}" type="text" class="form-control form-control-lg pr-4 shadow-none" id="{{ formsignupprofile.phone_number.id_for_label }}" />
                      <i class="fas fa-phone text-grey-m2 ml-n4"></i>
                      <label class="floating-label text-grey-l1 text-100 ml-n3" for="{{ formsignupprofile.phone_number.id_for_label }}">
                        {{ formsignupprofile.phone_number.label }}
                      </label>
                    </div>
                  </div>


                  <div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 mt-2">
                    <label class="d-inline-block mt-3 mb-0 text-secondary-d2">
                      <input type="checkbox" class="mr-1" id="id-agree" />
                      <span class="text-dark-m3">I have read and agree to <a href="#" class="text-blue-d2">terms</a></span>
                    </label>

                    <button type="submit" class="btn btn-success btn-block px-4 btn-bold mt-2 mb-3">
                      Sign Up
                    </button>
                  </div>
                </form>


                <div class="form-row w-100">
                  <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 d-flex flex-column align-items-center justify-content-center">

                    <hr class="brc-default-l2 mt-0 mb-2 w-100" />

                    <div class="p-0 px-md-2 text-dark-tp4 my-3">
                      Already a member?
                      <a class="text-blue-d1 text-600 mx-1" href="{% url 'authentication:signin' %}">
                        Login here
                      </a>
                    </div>

                  </div>
                </div>
              </div>
            </div>

          </div><!-- /.row -->

        </div><!-- /.col -->
      </div><!-- /.row -->

      {% include 'authentication/layout/copyright.html' %}
    </div>
  </div>

</div>
{% endblock %}